  adding-security-to-password[m
  changing-user-description[m
  delete-post[m
  deployment[m
* [32mdevelop[m
  edit-posts[m
  fixing-error-message-on-register/login[m
  master[m
  some-small-changes[m
  [31mremotes/origin/activities-view[m
  [31mremotes/origin/adding-posts/activities-to-database[m
  [31mremotes/origin/adding-security-to-password[m
  [31mremotes/origin/authentication-middleware[m
  [31mremotes/origin/delete-post[m
  [31mremotes/origin/delete-posts[m
  [31mremotes/origin/deployment[m
  [31mremotes/origin/develop[m
  [31mremotes/origin/edit-posts[m
  [31mremotes/origin/feat-user-and-activities-models[m
  [31mremotes/origin/fixing-error-message-on-register/login[m
  [31mremotes/origin/fixing-post-request-issues-login/register[m
  [31mremotes/origin/implementing-middleware-to-login/register[m
  [31mremotes/origin/login,register,views-and-routes[m
  [31mremotes/origin/login,register-routes[m
  [31mremotes/origin/login/signup-post-routes[m
  [31mremotes/origin/master[m
  [31mremotes/origin/populating-posts[m
  [31mremotes/origin/profile-view/route[m
  [31mremotes/origin/some-small-changes[m
  [31mremotes/origin/users-model-fix[m
